### ISSUE TITLE
The symbol for the cards doesn't print correctly in the terminal

### ISSUE THREAD

**Issue by puneetjohal** [kathleenwong1029/HablamosQueso#4]
![capture](https://user-images.githubusercontent.com/33487680/34951507-88d5f99e-f9e4-11e7-9697-185af538360b.PNG)

**Comment by puneetjohal** [comment]
Also:
11 = J
12 = Q
13 = K
1 = A
So those symbols should show up instead of the numeric values you feel

**Comment by kathleenwong1029** [comment]
fixed it ! and it prints correctly on mac

**Comment by kathleenwong1029** [comment]
<img width="502" alt="screen shot 2018-01-15 at 8 12 29 pm" src="https://user-images.githubusercontent.com/32499066/34967451-eff13c50-fa30-11e7-9aba-92dfce3e7e6f.png">
